apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: news-engine
  labels:
    app: publisher
    component: webserver
    part-of: news-engine
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: publisher