apiVersion: v1
kind: ConfigMap
metadata:
  name: rss-feeds-config
  namespace: news-engine
  labels:
    app: rss-fetcher
    component: config
    part-of: news-engine
data:
  feeds.yaml: |
    # RSS Feed Configuration
    # Each feed has: url, outlet name, and fetch interval (minutes)
    # All feeds are from non-subscription public news sources
    feeds:
      - url: "https://feeds.bbci.co.uk/news/rss.xml"
        outlet: "BBC News"
        interval: 15
        category: "news"
        
      - url: "https://www.theguardian.com/world/rss"
        outlet: "The Guardian World"
        interval: 20
        category: "news"
        
      - url: "https://www.aljazeera.com/xml/rss/all.xml"
        outlet: "Al Jazeera"
        interval: 20
        category: "news"
        
      - url: "https://feeds.npr.org/1001/rss.xml"
        outlet: "NPR News"
        interval: 30
        category: "news"
        
      - url: "https://rss.dw.com/rdf/rss-en-all"
        outlet: "Deutsche Welle"
        interval: 30
        category: "news"
        
      - url: "https://feeds.feedburner.com/TechCrunch/"
        outlet: "TechCrunch"
        interval: 20
        category: "news"

    # Default settings for all feeds
    defaults:
      interval: 30
      timeout: 30
      retries: 3
      user_agent: "K8s-News-Engine/1.0"