apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: news-engine
  labels:
    app: postgresql
    component: database
    part-of: news-engine
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgresql