# Claude Subagents Configuration for K8s News Engine Project
# This file registers all available subagents for use in this project

agents:
  - name: k8s-engineer
    description: "Kubernetes deployment and manifest specialist for creating and managing K8s resources"
    file: agents/k8s-engineer.agent
    proactive: true
    triggers:
      - "kubernetes"
      - "k8s"
      - "deployment"
      - "manifest"
      - "pod"
      - "service"
      - "configmap"
    capabilities:
      - "Write Kubernetes manifests"
      - "Debug K8s deployments"
      - "Optimize resource configurations"
      - "Setup K8s networking"

  - name: devops-engineer
    description: "DevOps and CI/CD pipeline specialist for deployment automation"
    file: agents/devops-engineer.agent
    proactive: true
    triggers:
      - "ci/cd"
      - "pipeline"
      - "deployment"
      - "automation"
      - "monitoring"
      - "docker"
    capabilities:
      - "Setup CI/CD pipelines"
      - "Configure GitOps workflows"
      - "Implement monitoring and alerting"
      - "Automate deployment processes"

  - name: docker-engineer
    description: "Docker containerization and optimization specialist"
    file: agents/docker-engineer.agent
    proactive: true
    triggers:
      - "docker"
      - "dockerfile"
      - "container"
      - "image"
      - "alpine"
    capabilities:
      - "Write optimized Dockerfiles"
      - "Container security"
      - "Multi-stage builds"
      - "Image optimization"

  - name: database-engineer
    description: "Database design and PostgreSQL specialist"
    file: agents/database-engineer.agent
    proactive: true
    triggers:
      - "database"
      - "postgresql"
      - "sql"
      - "schema"
      - "migration"
    capabilities:
      - "Database schema design"
      - "SQL query optimization"
      - "Migration scripts"
      - "PostgreSQL configuration"

  - name: python-analytics
    description: "Python analytics and machine learning specialist"
    file: agents/python-analytics.agent
    proactive: true
    triggers:
      - "python"
      - "analytics"
      - "ml"
      - "scikit-learn"
      - "nltk"
      - "pandas"
    capabilities:
      - "Python data analysis"
      - "Machine learning pipelines"
      - "NLP processing"
      - "Analytics optimization"

# Project-specific agent preferences
project_preferences:
  primary_agents:
    - k8s-engineer
    - devops-engineer
    - docker-engineer
  auto_invoke:
    - pattern: "*.yaml"
      agent: k8s-engineer
    - pattern: "Dockerfile*"
      agent: docker-engineer
    - pattern: "deploy.sh"
      agent: devops-engineer
    - pattern: "*.sql"
      agent: database-engineer
    - pattern: "*.py"
      agent: python-analytics

# Agent invocation settings
settings:
  auto_suggest: true  # Automatically suggest relevant agents based on context
  multi_agent: true   # Allow multiple agents to work on complex tasks
  verbose: false      # Show agent reasoning in responses