# Claude Subagents Configuration for K8s News Engine Project
# This file registers all available subagents for use in this project

agents:
  - name: k8s-engineer
    description: "Kubernetes deployment and manifest specialist"
    file: k8s-engineer.md
    triggers:
      - "kubernetes"
      - "k8s"
      - "deployment"
      - "manifest"
      - "pod"
      - "service"
      - "configmap"
    capabilities:
      - "Write Kubernetes manifests"
      - "Debug K8s deployments"
      - "Optimize resource configurations"
      - "Setup K8s networking"

  - name: k8s-devops-engineer
    description: "Kubernetes DevOps and CI/CD pipeline specialist"
    file: k8s-devops-engineer.md
    triggers:
      - "ci/cd"
      - "pipeline"
      - "gitops"
      - "argocd"
      - "helm"
      - "deployment automation"
    capabilities:
      - "Setup CI/CD pipelines"
      - "Configure GitOps workflows"
      - "Implement Helm charts"
      - "Setup monitoring and logging"

  - name: k8s-admin
    description: "Kubernetes cluster administration specialist"
    file: k8s-admin.md
    triggers:
      - "cluster"
      - "rbac"
      - "security"
      - "namespace"
      - "node"
      - "kubectl"
    capabilities:
      - "Configure RBAC policies"
      - "Manage cluster security"
      - "Setup namespaces and quotas"
      - "Troubleshoot cluster issues"

  - name: devops-engineer
    description: "General DevOps and infrastructure automation specialist"
    file: devops-engineer.md
    triggers:
      - "infrastructure"
      - "terraform"
      - "ansible"
      - "automation"
      - "monitoring"
    capabilities:
      - "Infrastructure as Code"
      - "Configuration management"
      - "Monitoring setup"
      - "Automation scripting"

  - name: devops-docker-engineer
    description: "Docker containerization and optimization specialist"
    file: devops-docker-engineer.md
    triggers:
      - "docker"
      - "dockerfile"
      - "container"
      - "image"
      - "registry"
      - "compose"
    capabilities:
      - "Write optimized Dockerfiles"
      - "Multi-stage builds"
      - "Container security"
      - "Docker Compose configurations"

  - name: devops-ai-mcp-engineer
    description: "AI/ML operations and MCP integration specialist"
    file: devops-ai-mcp-engineer.md
    triggers:
      - "mcp"
      - "ai"
      - "ml"
      - "model"
      - "inference"
      - "mlops"
    capabilities:
      - "Setup MCP servers"
      - "ML model deployment"
      - "AI pipeline automation"
      - "Inference optimization"

  - name: frontend-developer
    description: "Frontend web development specialist"
    file: frontend-developer.md
    triggers:
      - "frontend"
      - "react"
      - "vue"
      - "ui"
      - "web"
      - "javascript"
      - "typescript"
    capabilities:
      - "React/Vue development"
      - "UI/UX implementation"
      - "Frontend optimization"
      - "API integration"

  - name: software-team-lead
    description: "Software project management and architecture specialist"
    file: software-team-lead.md
    triggers:
      - "architecture"
      - "design"
      - "planning"
      - "team"
      - "project"
      - "roadmap"
    capabilities:
      - "System architecture design"
      - "Project planning"
      - "Code review practices"
      - "Team coordination"

  - name: atlassian-cloud-administrator
    description: "Atlassian Cloud suite administration specialist"
    file: atlassian-cloud-administrator.md
    triggers:
      - "atlassian"
      - "confluence"
      - "bitbucket"
      - "jira"
      - "admin"
    capabilities:
      - "Atlassian suite setup"
      - "User management"
      - "Workflow configuration"
      - "Integration setup"

  - name: jira-cloud-administrator
    description: "Jira Cloud configuration and workflow specialist"
    file: jira-cloud-administrator.md
    triggers:
      - "jira"
      - "workflow"
      - "issue"
      - "sprint"
      - "agile"
      - "kanban"
    capabilities:
      - "Jira workflow design"
      - "Custom fields and screens"
      - "Automation rules"
      - "Reporting setup"

# Project-specific agent preferences
project_preferences:
  primary_agents:
    - k8s-engineer
    - k8s-devops-engineer
    - devops-docker-engineer
  auto_invoke:
    - pattern: "*.yaml"
      agent: k8s-engineer
    - pattern: "Dockerfile*"
      agent: devops-docker-engineer
    - pattern: "deploy.sh"
      agent: k8s-devops-engineer

# Agent invocation settings
settings:
  auto_suggest: true  # Automatically suggest relevant agents based on context
  multi_agent: true   # Allow multiple agents to work on complex tasks
  verbose: false      # Show agent reasoning in responses